version = "0.1"

[assemblers]
gas = true
go = false
z80 = false
masm = false
nasm = false

[instruction_sets]
x86 = false
x86_64 = true
z80 = false
arm = false
riscv = false

[opts]
#compiler = "gcc"
diagnostics = true
default_diagnostics = true
